In [1]:
from prompt_utils import build_prompt
from data_utils import create_submission, parse_predictions, create_comparison_df, read_dataset
from semevalpolar.llm import custom_rules
from semevalpolar.llm.main import test_run, create_gen, create_response
from tqdm import tqdm
from semevalpolar.utils import get_project_root

from custom_rules import apply_rules

import os
import ast

D:\projects\mldl\semevalpolar

In [2]:
batch_size = 10
data_path = os.path.join(get_project_root(), 'data', 'dev_phase', 'subtask1', 'train', 'eng.csv')
gen = create_gen(data_path, batch_size=batch_size, randomize=True)
generator_list = list(gen)

In [3]:
df = read_dataset(data_path)

In [4]:
predictions = []
usages = []

In [5]:
for batch in tqdm(generator_list[:30]):
    response = test_run(batch, prompt_path="prompt-ds-main-classifier.txt")
    predictions.append(parse_predictions(response.output_text))
    usages.append(response.usage)

100%|██████████| 30/30 [03:05<00:00,  6.20s/it]

In [16]:
len(predictions)

30

In [17]:
flat = [x for sub in predictions for x in sub]

In [18]:
ground_truths = []

In [19]:
for i in range(len(flat) // 10):
    for x in generator_list[i]["polarization"]:
        ground_truths.append(x)

In [20]:
texts = []

for i in range(len(predictions)):
    for j in range(batch_size):
        texts.append(generator_list[i]["text"].iloc[j])

In [21]:
from sklearn.metrics import confusion_matrix

comparison = create_comparison_df(flat, ground_truths, texts)
cm = confusion_matrix(comparison["Ground Truth"], comparison["Predicted"], labels=[0, 1])
cm

array([[146,  50],
       [ 12,  92]])

In [22]:
from sklearn.metrics import accuracy_score

accuracy_score(comparison["Ground Truth"], comparison["Predicted"])

0.7933333333333333

In [23]:
comparison

,Predicted,Ground Truth,Text
0,1,1,Imagine blaming this on Israel instead of Hamas
1,1,1,Blinken is the Butcher of Blinken ButcherOfGaz...
2,0,0,"And as far as your gun control, Chicago knows ..."
3,0,0,All the spoilers are on Fox News daily.
4,1,1,Are red states stealing from California?
...,...,...,...
295,0,0,"Sometimes, history change with some flow. Eg. ..."
296,1,1,You mean voter fraud ? Thats Red.
297,0,0,Did Kamala Harris run this strategy?
298,0,0,The Queen is not a religion or a national iden...
299,1,1,"The Abortion issue was a plan leak , its all p..."

In [27]:
correct = comparison[comparison["Predicted"] == comparison["Ground Truth"]]
correct

,Predicted,Ground Truth,Text
0,1,1,Imagine blaming this on Israel instead of Hamas
1,1,1,Blinken is the Butcher of Blinken ButcherOfGaz...
2,0,0,"And as far as your gun control, Chicago knows ..."
3,0,0,All the spoilers are on Fox News daily.
4,1,1,Are red states stealing from California?
...,...,...,...
295,0,0,"Sometimes, history change with some flow. Eg. ..."
296,1,1,You mean voter fraud ? Thats Red.
297,0,0,Did Kamala Harris run this strategy?
298,0,0,The Queen is not a religion or a national iden...
299,1,1,"The Abortion issue was a plan leak , its all p..."

In [25]:
wrong = comparison[comparison["Ground Truth"] != comparison["Predicted"]]
wrong[wrong["Predicted"] == 1]

,Predicted,Ground Truth,Text
21,1,0,War crimes tweeted in real time.
24,1,0,They said voter fraud doesnt exist tho...
33,1,0,Israel is attempting genocide and the U.S. is ...
40,1,0,"CSG holds meeting, students speak on IsraelHam..."
42,1,0,theyre not taking down the Iron dome. ffs people.
43,1,0,Calling for Impeachment. ASAP. impeachmentnow ...
44,1,0,Israel closes border crossing to Gaza workers ...
46,1,0,Donating to the IDF is Lawful Good. I am confu...
50,1,0,Ohio Republicans introduce bill to ban public ...
58,1,0,Im so glad that Joe Biden pardoned Hunter Bide...
64,1,0,He is a Psycho. CANADAS CONSERVATIVE LEADER IS...
74,1,0,THE DIXIECRAT GOPAfrican American News and Issues
76,1,0,This the voter fraud you seek??
78,1,0,He has Russia and Ukraine discussing a ceasefi...
80,1,0,Oh ya think? What about the rest of the swing ...
81,1,0,"Thanks, Snowflake! Youre the best!"
90,1,0,Donate to friends of the IDF!
97,1,0,Texas Republicans Target Climate Science in Te...
99,1,0,Californias Republicans should break from Donald
100,1,0,Former Michigan GOP spokesperson testifies fak...
105,1,0,theyve been the same Israeli encroachment
114,1,0,Have a happy Wednesday everyone. Remember to t...
116,1,0,AOC and Kamala Harris dont really care.
126,1,0,Blue states need to start building our own mil...
127,1,0,Everything that I dont like is post modern neo...
145,1,0,Absolutely no evidence of voter fraud Democrats
147,1,0,All immigration is good remember?
148,1,0,Once while i encourage ppl in swing states to ...
154,1,0,Muslim Turkey follows the sharia. Erdogan is d...
160,1,0,So a 5x reduction in support is proof of the n...
164,1,0,I wasnt discussing Bidens Zionism.
170,1,0,He complaining about the border while Biden ge...
171,1,0,Traitor raising anothe man hating traitor schyzo
179,1,0,Think we will have another pandemic and impeac...
185,1,0,eu and now anti immigration. . Are they all ai...
200,1,0,Image makers However turkey host Hamas.
201,1,0,Reminds me of Putin propaganda.
202,1,0,Yes! This is what I want to see on MSNBC!!
203,1,0,Was Trumps ethnic nationalism the key to his s...
220,1,0,How this Dutch taxi driver signed a recording ...
226,1,0,We need to stay a group occupy Democrats. Well...
234,1,0,Stupids order to block all grants and loans un...
235,1,0,Whats your plan for the open borders Bobby???
254,1,0,lol burner account like they be his human shie...
257,1,0,Economic sanctions have more civilian casualti...
258,1,0,Sanctions should mean sanctions and just not s...
260,1,0,"Thank you, Patty and Senate Democrats!!"
264,1,0,Time to abort the filibuster and the electoral...
268,1,0,The second amendment is more important now tha...
290,1,0,The IDF needs some B52s.

In [29]:
submission = create_submission(df, flat)

In [30]:
submission.to_csv(os.path.join(get_project_root(), 'predictions', 'subtask_1', 'pred_eng.csv'), index=False)